
package org.example.serial_service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SerialWebService", targetNamespace = "http://tx.wsdl.java/")
@XmlSeeAlso({
    org.example.serial_service.ObjectFactory.class
})
public interface SerialWebService {


    /**
     * 
     * @return
     *     returns java.util.List<org.example.serial_service.Serial>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSerial", targetNamespace = "http://tx.wsdl.java/", className = "org.example.serial_service.GetSerial")
    @ResponseWrapper(localName = "getSerialResponse", targetNamespace = "http://tx.wsdl.java/", className = "org.example.serial_service.GetSerialResponse")
    @Action(input = "http://tx.wsdl.java/SerialWebService/getSerialRequest", output = "http://tx.wsdl.java/SerialWebService/getSerialResponse")
    public List<Serial> getSerial();

}
