
package com.labs.client.serial_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SerialService", targetNamespace = "http://tx.wsdl.java/", wsdlLocation = "http://localhost:8081/SerialService?wsdl")
public class SerialService
    extends Service
{

    private final static URL SERIALSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERIALSERVICE_EXCEPTION;
    private final static QName SERIALSERVICE_QNAME = new QName("http://tx.wsdl.java/", "SerialService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/SerialService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERIALSERVICE_WSDL_LOCATION = url;
        SERIALSERVICE_EXCEPTION = e;
    }

    public SerialService() {
        super(__getWsdlLocation(), SERIALSERVICE_QNAME);
    }

    public SerialService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERIALSERVICE_QNAME, features);
    }

    public SerialService(URL wsdlLocation) {
        super(wsdlLocation, SERIALSERVICE_QNAME);
    }

    public SerialService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERIALSERVICE_QNAME, features);
    }

    public SerialService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SerialService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SerialWebService
     */
    @WebEndpoint(name = "SerialWebServicePort")
    public com.labs.client.serial_service.SerialWebService getSerialWebServicePort() {
        return super.getPort(new QName("http://tx.wsdl.java/", "SerialWebServicePort"), SerialWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SerialWebService
     */
    @WebEndpoint(name = "SerialWebServicePort")
    public SerialWebService getSerialWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tx.wsdl.java/", "SerialWebServicePort"), SerialWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERIALSERVICE_EXCEPTION!= null) {
            throw SERIALSERVICE_EXCEPTION;
        }
        return SERIALSERVICE_WSDL_LOCATION;
    }

}
